[build-system]
requires = [
    "scikit-build-core",
    "pxr-arch-dev==25.8.*",
    "pxr-tf-dev==25.8.*",
]
build-backend = "scikit_build_core.build"

[project]
name = "pxr-js-dev"
version = "25.8"
description = "C++ headers and CMake config for developing with pxr-js"
readme = "README.md"
requires-python = ">=3.8"
license-files = ["LICENSE.txt", "NOTICE.txt"]
keywords = ["pixar", "open-usd", "dev"]
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows :: Windows 10",
]
dependencies = [
    "pxr-arch-dev==25.8.*",
    "pxr-tf-dev==25.8.*",
]

[project.urls]
Repository = "https://github.com/untwine/pxr-js"

[tool.scikit-build]
cmake.version = ">=3.23,<4.2"
cmake.args = [
    "-DBUILD_TESTS=OFF",
    "-DBUILD_SHARED_LIBS=ON",
    "-DCMAKE_INSTALL_LIBDIR=pxr-js/lib",
    "-DCMAKE_INSTALL_INCLUDEDIR=pxr-js/include",
    "-DCMAKE_INSTALL_DATAROOTDIR=pxr-js",

    # Set minimum macOS version to 10.13 to allow use of std::get<T> with std::variant
    "-DCMAKE_OSX_DEPLOYMENT_TARGET=10.13"
]
sdist.exclude = ["test", ".github"]
